#if !canImport(ObjectiveC)
import XCTest

extension StorageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StorageTests = [
        ("testDelete", testDelete),
        ("testFetch", testFetch),
        ("testPathWithWhitespace", testPathWithWhitespace),
        ("testStore", testStore),
        ("testWrite", testWrite),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(StorageTests.__allTests__StorageTests),
    ]
}
#endif
